### ISSUE TITLE
Trackbar value isn't rounded properly and shows long float number.

### ISSUE THREAD

**Issue by Banjaji** [RAX-Anomaly/Anomaly-Mod-Configuration-Menu#8]
I get the (decorative) problem if the option is eg. {id = "something", type = "track", val = 2, min = 0, max = 10, step = 0.05, def = 1}. When I move the slider into some positions the shown float isn't rounded properly and shows stuff like "8.450001" or "9.900001" instead of "8.45" or "9.9".

**Comment by ravenascendant** [comment]
Limitations of xray lua's floating point numbers.
look up the optional parameter [prec] in the documentation, it is there to solve this problem.
